### PR TITLE
Resolves #5, publish each favicon 'flavor' as dedicated svg file

### LINKED ISSUE #5: Extract each favicon "flavor" into a dedicated svg file
Disclaimer: I'm not a svg expert!

I guess this should be possible to extract each version of the favicon from the sprite but I couldn't figure it out. For practical reasons, I think we should provide each version as a single svg file, what do you think ?

For reference, my initial goal was to integrate the favicon on the browser extension: https://developer.mozilla.org/fr/Add-ons/WebExtensions/API/browserAction/setIcon

### PR DESCRIPTION
**Pull request by ggrossetie**
Each favicon at 16px*16px

logo-favicon-outline-bw
logo-favicon-fill-color
logo-favicon-outline-color
logo-favicon-fill-bw

I've also added two new favicon without outline (only the letter A) for comparison purposes

logo-favicon-nooutline-color-bold
logo-favicon-nooutline-color

Resolves #5 

//cc @mojavelinux @mmajko

### CODE REVIEW

**Comment by marianhlavac** [comment]
We should move the favicon to the `logo/icon` folder, because of 
https://github.com/asciidoctor/brand/pull/10#issuecomment-429501045.

Do you agree?

**Comment by mojavelinux** [comment]
I think the favicon should be a generated file (which the script will produce).

Btw, this PR is now superseded by #10 and should be closed to avoid confusion. @Mogztter do you agree to that?

**Comment by mojavelinux** [comment]
The repository now has a script to export the logos to PNG, including creating the favicon.

@Mogztter can this PR be closed?

**Comment by ggrossetie** [comment]
@mojavelinux Yes sure, nice work :+1:

**Comment by mojavelinux** [comment]
Thanks for giving me the starting point!

If any additional refinement is needed, let's handle it in a separate issue.

Btw, the favicon is now live on asciidoctor.org! :tada:

**Pull request closed without merging**
